{
 "title": "Serving Overview",
 "description": "Serving generic status",
 "refresh": "10s",
 "panels": [
  {
   "title": "Throughput",
   "type": "stat",
   "description": "Average number of requests processed per second.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "In-Flight Requests",
   "type": "gauge",
   "description": "Current number of active (not yet completed) requests per path.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(http_inflight_requests)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Error Rate (%)",
   "type": "stat",
   "description": "Percentage of requests returning 4xx or 5xx errors.",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(http_requests_total{status=~\"4..|5..\"}[5m])) / sum(rate(http_requests_total[5m]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Size (AVG)",
   "type": "timeseries",
   "description": "Average size of incoming request payloads (bytes).",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (path) (rate(http_request_size_bytes_sum[5m]) / rate(http_request_size_bytes_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Size (Avg)",
   "type": "timeseries",
   "description": "Average size of HTTP responses (bytes).",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (path) (rate(http_response_size_bytes_sum[5m]) / rate(http_response_size_bytes_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency avg",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (path, status) (rate(http_request_duration_seconds_sum[5m])) \r\n/ \r\nsum by (path, status) (rate(http_request_duration_seconds_count[5m]))"
    }
   ]
  },
  {
   "title": "Requests by Endpoint",
   "type": "timeseries",
   "description": "Traffic distribution across API endpoints.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum by (path) (rate(http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}